[package]
name = "game"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
psp_mesh_writer = { path = "../crates/mesh_writer" }

psp = { workspace = true }
uninit = { workspace = true }
