[package]
name = "psp_file_formats"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
aligned-vec = { workspace = true }
postcard = { workspace = true }
serde = { workspace = true }
